# docker-compose.yml (Versi Revisi & Stabil)
# Jalankan dengan 'docker-compose up -d --build'

services:
  # Layanan ini menyediakan lingkungan (replika lokal) untuk Internet Computer (IC).
  # Auto-deploy mode: Automatically starts replica and deploys canisters
  # Manual mode: Requires manual deployment via docker exec commands
  dfx-replica:
    image: dfinity/ic-build
    container_name: aegis-dfx-replica
    ports:
      # Port ini digunakan oleh replika lokal IC.
      - "4943:4943"
    working_dir: /work
    volumes:
      # Mount source code backend blockchain ke dalam working directory.
      - ./services/2-backend-blockchain-icp:/work
      # Mount the auto-deploy script
      - ./services/3-backend-ai-agents/auto_deploy.sh:/work/auto_deploy.sh
    environment:
      # Set to 'auto' for automatic deployment, 'manual' for manual deployment
      - DEPLOY_MODE=${DEPLOY_MODE:-auto}
    # Auto-deploy mode: automatically start and deploy
    # Manual mode: keep container running for manual deployment
    command: >
      bash -c "
        chmod +x /work/auto_deploy.sh;
        if [ \"$$DEPLOY_MODE\" = \"auto\" ]; then
          echo '🚀 Starting automatic deployment...';
          /work/auto_deploy.sh;
        else
          echo '📋 Manual deployment mode. Use: docker exec -it aegis-dfx-replica bash';
          echo '   Then run: dfx start --background --host 0.0.0.0 && dfx deploy';
          tail -f /dev/null;
        fi
      "

  # === Layanan Agen AI ===
  # Catatan: Semua agen di bawah ini bergantung pada 'dfx-replica'
  # dan akan restart jika terjadi kegagalan.

  oracle-agent:
    build:
      context: ./services/3-backend-ai-agents
      dockerfile: Dockerfile
    container_name: aegis-oracle-agent
    command: python agents/oracle_agent.py
    ports:
      - "8001:8001"
    environment:
      # Variabel ini akan diisi setelah 'dfx deploy' berhasil.
      - EVENT_FACTORY_CANISTER_ID=${EVENT_FACTORY_CANISTER_ID}
      # Mengarahkan URL ICP ke layanan Docker dfx-replica.
      - ICP_URL=http://dfx-replica:4943
    volumes:
      # Mount identity.pem untuk otentikasi.
      - ./services/3-backend-ai-agents/identity.pem:/app/identity.pem
      # Mount seluruh direktori .dfx/local agar canister_ids.json dan file lainnya tersedia.
      - ./services/2-backend-blockchain-icp/.dfx/local:/app/dfx-local
    depends_on:
      - dfx-replica
    restart: on-failure

  validator-agent:
    build:
      context: ./services/3-backend-ai-agents
      dockerfile: Dockerfile
    container_name: aegis-validator-agent
    command: python agents/validator_agent.py
    ports:
      - "8002:8002"
    environment:
      - EVENT_FACTORY_CANISTER_ID=${EVENT_FACTORY_CANISTER_ID}
      - ICP_URL=http://dfx-replica:4943
    volumes:
      - ./services/3-backend-ai-agents/identity.pem:/app/identity.pem
      - ./services/2-backend-blockchain-icp/.dfx/local:/app/dfx-local
    depends_on:
      - dfx-replica
    restart: on-failure
    networks:
      - aegis-net

  action-agent:
    build:
      context: ./services/3-backend-ai-agents
      dockerfile: Dockerfile
    container_name: aegis-action-agent
    command: python agents/action_agent.py
    ports:
      - "8003:8003"
    environment:
      - EVENT_FACTORY_CANISTER_ID=${EVENT_FACTORY_CANISTER_ID}
      - ICP_URL=http://dfx-replica:4943
    volumes:
      - ./services/3-backend-ai-agents/identity.pem:/app/identity.pem
      - ./services/2-backend-blockchain-icp/.dfx/local:/app/dfx-local
    depends_on:
      - dfx-replica
    restart: on-failure
    networks:
      - aegis-net

networks:
  aegis-net:
    driver: bridge