# docker-compose.yml (Versi Manual & Paling Stabil)
services:
  # Layanan ini HANYA akan menyediakan "ruang mesin" dengan perkakas dfx.
  dfx-replica:
    image: dfinity/sdk
    container_name: aegis-dfx-replica
    ports:
      - "4943:4943"
    working_dir: /work
    volumes:
      - ./services/2-backend-blockchain-icp:/work
    # Perintah ini hanya akan menjaga container tetap hidup.
    command: tail -f /dev/null

  # (Semua layanan agen AI di bawah ini tidak perlu diubah)
  oracle-agent:
    build:
      context: ./services/3-backend-ai-agents
      dockerfile: Dockerfile
    # ... sisa konfigurasinya sama ...
  validator-agent:
    build:
      context: ./services/3-backend-ai-agents
      dockerfile: Dockerfile
    # ... sisa konfigurasinya sama ...
  action-agent:
    build:
      context: ./services/3-backend-ai-agents
      dockerfile: Dockerfile
    # ... sisa konfigurasinya sama ...
