[dependencies]
base = "0.14.1"
memory-region = "1.0.0"
motoko-base = "https://github.com/dfinity/motoko-base#master@df83fbfb4b196910d8e1f789a7e2ca91dd734378"

[toolchain]
moc = "0.15.1"

[requirements]
moc = "0.15.1"