services:
  oracle-agent:
    build: .
    container_name: aegis-oracle-agent
    command: python agents/oracle_agent.py
    restart: on-failure
    network_mode: "host"

  validator-agent:
    build: .
    container_name: aegis-validator-agent
    command: python agents/validator_agent.py
    restart: on-failure
    network_mode: "host"

  action-agent:
    build: .
    container_name: aegis-action-agent
    command: python agents/action_agent.py
    restart: on-failure
    network_mode: "host"
    volumes:
      - ../identity.pem:/app/identity.pem:ro
      - ../.dfx/local:/app/dfx-local:ro