services:
  validator-agent:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /app/agents/validator_agent.py
    env_file:
      - ../.env
    environment:
      - VALIDATOR_AGENT_SEED=${VALIDATOR_AGENT_SEED}
      - ACTION_AGENT_ADDRESS=${ACTION_AGENT_ADDRESS}
      - CANISTER_IDS_PATH=/app/dfx-local/canister_ids.json
      - IDENTITY_PEM_PATH=/app/identity.pem
    ports:
      - "8002:8002"
    restart: ${AGENT_RESTART_POLICY:-unless-stopped}
    # SECURITY: Add resource limits and security options
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
    volumes:
      - ./.dfx/local/canister_ids.json:/app/dfx-local/canister_ids.json:ro
      - ./identity.pem:/app/identity.pem:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  oracle-agent:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /app/agents/oracle_agent.py
    env_file:
      - ../.env
    environment:
      - ORACLE_AGENT_SEED=${ORACLE_AGENT_SEED}
      - VALIDATOR_AGENT_ADDRESS=${VALIDATOR_AGENT_ADDRESS}
      - CANISTER_IDS_PATH=/app/dfx-local/canister_ids.json
      - IDENTITY_PEM_PATH=/app/identity.pem
    ports:
      - "8001:8001"
    restart: ${AGENT_RESTART_POLICY:-unless-stopped}
    volumes:
      - ./.dfx/local/canister_ids.json:/app/dfx-local/canister_ids.json:ro
      - ./identity.pem:/app/identity.pem:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  action-agent:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /app/agents/action_agent.py
    env_file:
      - ../.env
    environment:
      - ACTION_AGENT_SEED=${ACTION_AGENT_SEED}
      - CANISTER_IDS_PATH=/app/dfx-local/canister_ids.json
      - IDENTITY_PEM_PATH=/app/identity.pem
      - ICP_URL=${ICP_URL}
    ports:
      - "8004:8004"
    depends_on:
      - validator-agent
      - oracle-agent
    restart: ${AGENT_RESTART_POLICY:-unless-stopped}
    volumes:
      - ./.dfx/local/canister_ids.json:/app/dfx-local/canister_ids.json:ro
      - ./identity.pem:/app/identity.pem:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"